---
config:
  layout: elk
---

classDiagram
    class EventBus {
        -Queues: Dict[EventTypes, Queue[Event]]
        -Listeners: Dict[EventTypes, Func[Event, void]]
        +Publish(event: Event) void
        +Subscribe(eventType: EventTypes, callback: Func[Event, void]) void
    }

    class Engine {
        + SystemRegistry: SystemRegistry
        + EventBus: EventBus
        + World: World

        + Start(TimeDelta delta) void
    }

    class World {
        + Entities: Dict[EntityID, Entity]
        + EntityComponentIndex: Dict[Component, List[EntityID]]

        + Layers: Dict[LayerID, Layer]
        + LayerComponentIndex: Dict[Component, List[LayerID]]

        + Renderer: Renderer
        + InputHandler: InputHandler
    }

    class SystemRegistry {
        + Systems: Dict[string, System]
        + Register(System system, string Identifier)
    }


    class Renderer {
        # update(TimeDelta delta) void
        - renderStrategy: RenderingStrategy
    }

    class InputHandler {
        # update(TimeDelta delta) void
    }

    class System {
        <<interface>>
        + update(TimeDelta delta) void
    }

    class Component {
        <<interface>>
    }


Engine *-- World
Engine *-- SystemRegistry
Engine *-- EventBus
World *-- Renderer
World *-- InputHandler

System <|-- Renderer
System <|-- InputHandler